### ISSUE TITLE
restore: root-tree.c:46: btrfs_find_last_root: Assertion `!(path->slots[0] == 0)' failed.

### ISSUE THREAD

**Issue by eyecreate** [josefbacik/btrfs-progs#2]
Running some of the tools here, including restore and btrfsck, fail on this method on a btrfs partition that fails to mount.

Stepping through with gdb, path.slots consists all of zeros and path.nodes usually only have the first two be non-zero.

Can supply more info if needed.

**Comment by eyecreate** [comment]
A recent commit addresses this condition, so I guess this specific error is closed.(unless the fix was incomplete.)

Too bad it still doesn't assemble a tree of my filesystem.

**Comment by Rixsus** [comment]
I still have same prolem, Kernel 3.2.6, btrfstools - compiled from git, and for every btrfs tools I get
btrfsck: root-tree.c:46: btrfs_find_last_root: Assertion `!(path->slots[0] == 0)' failed.

So can somebody solve this problem. I'm waiting probably 6 months for some recovery tool...
